services:
  - type: web
    name: mart-vet-api
    env: docker
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: HF_TOKEN
        sync: false
      - key: HF_SYMPTOMS_MODEL_ID
        sync: false
      - key: HF_IMAGE_MODEL_ID
        sync: false
      - key: HF_MODEL_REPO
        sync: false
      - key: HF_MODEL_FILENAME
        value: best_model.pkl
      - key: API_TITLE
        value: Tech Challenge Animal Condition Inference API
      - key: API_DESCRIPTION
        value: API de inferencia que integra modelos Hugging Face para sintomas, imagem e modelo tabular de condicao animal.
      - key: API_VERSION
        value: 1.0.0
      - key: API_ENV
        value: prod
      - key: TRIAGE_POSITIVE_LABELS
        value: emergencia,urgente,grave
      - key: TRIAGE_HIGH_THRESHOLD
        value: "0.85"
      - key: TRIAGE_MEDIUM_THRESHOLD
        value: "0.60"
      - key: ALLOWED_ORIGINS
        sync: false
